name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ALLOWED_FOLDERS: '.github/workflows file2'

    steps:
      - uses: actions/checkout@v2
        
      - name: "Check file existence"
        uses: andstor/file-existence-action@v1
        with:
          allow_failure: true
          files: "projects/chat_project/pom.xml, README.md"

      - id: changed-files
        name: Get changed files
        uses: jitterbit/get-changed-files@v1

      - id: changes_in_allowed_folders
        name: Are changes in correct folders
        run: |
          for changed_file in ${{ steps.changed-files.outputs.all }}; do
          
            found=false
            for folder in ${{ env.ALLOWED_FOLDERS }}; do
              if [[ $changed_file == $folder* ]]; then
                found=true
                break
              fi
            done
            
            if [[ $found == false ]]; then
              echo Action performed on file outside permited folder: $changed_file
              exit 1
            fi
            
          done

      - id: check-changed-md-file-content
        name: Are markup files correct
        run: |
          echo ${{ steps.changed-files.outputs.all }}
          for changed_file in ${{ steps.changed-files.outputs.all }}; do
            if [[ $changed_file == *.yml ]]; then
              
              cat sample_data_1.txt
              x = sed -n '2p'
              echo "x: ${x}."
              
              content=`cat ${changed_file}`
              echo "Contents: ${content}."
            fi
          done




















        
