name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ALLOWED_FOLDERS: '[".github/workflows","file2"]'

    steps:
      - uses: actions/checkout@v2
        
      - name: "Check file existence"
        uses: andstor/file-existence-action@v1
        with:
          allow_failure: true
          files: "projects/chat_project/pom.xml, README.md"

      - id: folder_list
        uses: lucaspinheirogit/list-from-string-array-action@v1.4.3
        with:
          stringArray: '[".github/workflows","file2"]'

      - id: changed-files
        uses: jitterbit/get-changed-files@v1

      - id: changes_in_allowed_folders
        run: |
          for folder in ${{ steps.folder_list.outputs.stringList }}; do
            echo "Contents: ${folder}."
          done


      - id: check-changed-md-file-content
        run: |
          for changed_file in ${{ steps.changed-files.outputs.all }}; do
            if [[ $changed_file == *.yml ]]; then
              content=`cat ${changed_file}`
              echo "Contents: ${content}."
            fi
          done




















        
