name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: "Check file existence"
        uses: andstor/file-existence-action@v1
        with:
          allow_failure: true
          files: "projects/chat_project/pom.xml, README.md"

      - id: changed-files
        uses: jitterbit/get-changed-files@v1

      - id: check-changed-md-file-content
        run: |
          for changed_file in ${{ steps.changed-files.outputs.all }}; do
            if [[ $changed_file == *.yml ]]; then
              content=`cat ${changed_file}`
              echo "Do something with this ${content}."
            fi
          done





























        
